package com.czweb.pojo;

import org.springframework.stereotype.Service;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {
    private int id;
    private String loginName;
    private String loginPwd;
    private String modifyLoginPwd;
    private String userName;
    private String email;
    private Integer failedLoginNum;
    private Integer maxLoginNum;
    private Integer pwdExpiryDay;
    private String lastPwdUpdateDate;
    private String lastPwdUpdateTime;
    private String userType;
    private String loginStatus;
    private String repeatLoginFlag;
    private Integer creatorId;
    private String createDate;
    private String createTime;
    private Integer updaterId;
    private String updateDate;
    private String updateTime;
    private String sessionId;
    private String reqIp;

    public UserInfo() {
    }

    public UserInfo(int id) {
        this.id = id;
    }

    public UserInfo(int id, String loginName, String loginPwd,
                    String modifyLoginPwd, String userName, String email,
                    Integer failedLoginNum, Integer maxLoginNum, Integer pwdExpiryDay,
                    String lastPwdUpdateDate, String lastPwdUpdateTime,
                    String userType, String loginStatus, Integer creatorId,
                    String createDate, String createTime, Integer updaterId,
                    String updateDate, String updateTime) {
        this.id = id;
        this.loginName = loginName;
        this.loginPwd = loginPwd;
        this.modifyLoginPwd = modifyLoginPwd;
        this.userName = userName;
        this.email = email;
        this.failedLoginNum = failedLoginNum;
        this.maxLoginNum = maxLoginNum;
        this.pwdExpiryDay = pwdExpiryDay;
        this.lastPwdUpdateDate = lastPwdUpdateDate;
        this.lastPwdUpdateTime = lastPwdUpdateTime;
        this.userType = userType;
        this.loginStatus = loginStatus;
        this.creatorId = creatorId;
        this.createDate = createDate;
        this.createTime = createTime;
        this.updaterId = updaterId;
        this.updateDate = updateDate;
        this.updateTime = updateTime;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getLoginPwd() {
        return this.loginPwd;
    }

    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    public String getModifyLoginPwd() {
        return this.modifyLoginPwd;
    }

    public void setModifyLoginPwd(String modifyLoginPwd) {
        this.modifyLoginPwd = modifyLoginPwd;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getFailedLoginNum() {
        return this.failedLoginNum;
    }

    public void setFailedLoginNum(Integer failedLoginNum) {
        this.failedLoginNum = failedLoginNum;
    }

    public Integer getMaxLoginNum() {
        return this.maxLoginNum;
    }

    public void setMaxLoginNum(Integer maxLoginNum) {
        this.maxLoginNum = maxLoginNum;
    }

    public Integer getPwdExpiryDay() {
        return this.pwdExpiryDay;
    }

    public void setPwdExpiryDay(Integer pwdExpiryDay) {
        this.pwdExpiryDay = pwdExpiryDay;
    }

    public String getLastPwdUpdateDate() {
        return this.lastPwdUpdateDate;
    }

    public void setLastPwdUpdateDate(String lastPwdUpdateDate) {
        this.lastPwdUpdateDate = lastPwdUpdateDate;
    }

    public String getLastPwdUpdateTime() {
        return this.lastPwdUpdateTime;
    }

    public void setLastPwdUpdateTime(String lastPwdUpdateTime) {
        this.lastPwdUpdateTime = lastPwdUpdateTime;
    }

    public String getUserType() {
        return this.userType;
    }

    public void setUserType(String userType) {
        this.userType = userType;
    }

    public String getLoginStatus() {
        return this.loginStatus;
    }

    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }

    /**
     * @return the repeatLoginFlag
     */
    public String getRepeatLoginFlag() {
        return repeatLoginFlag;
    }

    /**
     * @param repeatLoginFlag the repeatLoginFlag to set
     */
    public void setRepeatLoginFlag(String repeatLoginFlag) {
        this.repeatLoginFlag = repeatLoginFlag;
    }

    public Integer getCreatorId() {
        return this.creatorId;
    }

    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    public String getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public Integer getUpdaterId() {
        return this.updaterId;
    }

    public void setUpdaterId(Integer updaterId) {
        this.updaterId = updaterId;
    }

    public String getUpdateDate() {
        return this.updateDate;
    }

    public void setUpdateDate(String updateDate) {
        this.updateDate = updateDate;
    }

    public String getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public String getReqIp() {
        return reqIp;
    }

    public void setReqIp(String reqIp) {
        this.reqIp = reqIp;
    }

}
